### PR TITLE
Fix issue with research_sync plugin

### PR DESCRIPTION
**Pull request by Luciole0x**
Fix type issues when loading technologies and broadcasting progress.
Locally tested;
Researches sync when adding a new instance.
Was able to research on one instance and see progress from another instance while searching a second or same research.
No more errors in logs.

### CODE REVIEW

**Comment by Hornwitser** [comment]
Isn't this still broken though? If someone updates from alpha.13 the technologies.json file will contain data of the form
```ts
type TechnologiesJson = [string, { level: number, progress: number | null, researched: boolean }][]
```
But your updated code expects technologies.json to contain data of the of the form
```ts
type TechnologiesJson = [string, [string, number, number | null, boolean]][]
```

If you want to change the format of data stored on disk you need to write code that can load both the old and new format. But I don't see a good reason to change the format here.

**Comment by Luciole0x** [comment]
Looking at the previous changes I made I see what I misunderstood. I was using technologies Map as `Map<string, Technology>` where it was `Map<string, {  level:number, progress:number|undefined, researched:boolean }`.
The different Technology like type across confuse me.
I will add a distinct type, to make it work like before.

**Review by psihius — COMMENTED** [review]
The code looks good to me, I do have one request - can we try and update the tests please and cover the changes? 

I think it's time to put some effort into updating and improving the tests so we don't degrade the coverage.

**Review by Hornwitser — APPROVED** [review]

**Comment by Hornwitser** [comment]
I think that's a separate effort to this PR. The harness needed to test research_sync properly is non-trivial to write.

**Pull request merged**
