### PR TITLE
fix inventory_sync plugin 

### PR DESCRIPTION
**Pull request by Luciole0x**
Fix an issue with player_data / playerData property.

### CODE REVIEW

**Review by psihius — APPROVED** [review]
Seems okay to me, @Hornwitser your turn :)

**Review by Hornwitser — APPROVED** [review]
As a band aid this works, but there's clearly a deeper issue with the typings of plugins that need to be fixed. I'll look into that.

**Comment by Luciole0x** [comment]
Yes most of the issues comes from the `type ___ = any` in places like lib/src/plugin.ts but we cannot import the types from the other packages as it will create some circular dependency on the types and `tsc --build` fail as the output will overwrite .d.ts files used as input.
One possible solution may be to create the interfaces inside the lib package and make the implementations use those interfaces to prevent out of sync in the others packages.

**Comment by Hornwitser** [comment]
I was thinking about moving the instance base plugin to the `@clusterio/host` package. That way it could make use of the types from that package, but I'm not sure if that will create other issues.

**Pull request merged**
