### PR TITLE
Add timeout to invokeHook on plugins

### PR DESCRIPTION
**Pull request by Danielv123**
If a plugin fails to resolve its promise in a hook handler the slave would get stuck, preventing other plugins from processing their hooks. The only way to recover (in the case of a slave failing to stop properly) was a slave restart.

This PR adds a 15 second max processing time. After that time, the error will be logged and the next hook will be processed.

image

### CODE REVIEW

**Review by Hornwitser — CHANGES_REQUESTED** [review]
This leaks the timer, which means on shutdown you're going to end up waiting 15 seconds after last instance stopping for the timer to expire. You should probably be using lib/helpers.timeout here.

**Review by psihius — APPROVED** [review]

**Review by Hornwitser — CHANGES_REQUESTED** [review]
Now it's broken, returning the error instead of throwing it. Also creating an error instance when you don't use it isn't free since it has to create a stack traceback.

**Comment by Danielv123** [comment]
🤦‍♂️ I'll fix that and test it properly when I get home.

**Comment by Danielv123** [comment]
Not the prettiest solution, but it seems right. Try/catch needs to stay because hook can still throw. I used a string object to see if the returned value is an error or a response object of some kind. Afaik this cannot be bypassed when using a strict comparison, although I doubt anyone will intentionally try to make it throw.

**Review by psihius — APPROVED** [review]
Well, it seems you went through multiple iterations and applied some dark magic here, and since it's so dark like it's from DC universe, I don't have any reason to doubt it's what is needed here.

:rofl:

**Comment by Hornwitser** [comment]
Seems a bit odd of a way to do it for me. You can use an empty object to check if the action timed out like this
```js
const timedOut = {}
let result = await helpers.timeout(plugin[hook](...args), 15000, timedOut);
if (result === timedOut) {
    throw new Error(`Invoking hook ${hook} timed out for plugin ${name}`);
}
```

**Comment by Danielv123** [comment]
That is essentially what I am doing, but I wanted the code to be more descriptive. `let x = {}` is 40% faster than `let x = new String("Error message")` but I doubt the 20ns makes much of a difference here. Should I change it?

**Review by Hornwitser — APPROVED** [review]

**Pull request merged**
